const {chromium}=require('./test-tools/node_modules/playwright');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const chromiumPath=()=>process.env.CHROMIUM_PATH||['C:/Users/agilb/AppData/Local/ms-playwright/chromium-1187/chrome-win/chrome.exe','/opt/pw-browsers/chromium'].find(file=>require('node:fs').existsSync(file));
const root=path.resolve(__dirname,'..');
const out=path.join(root,'verificacao');fs.mkdirSync(out,{recursive:true});
const results=[];
const check=(name,fn)=>{assert.ok(fn,name);results.push(name);};
(async()=>{
  const browser=await chromium.launch({executablePath:chromiumPath(),headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  try{
    const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
    await context.setOffline(true);
    const page=await context.newPage(),errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    await page.goto(pathToFileURL(path.join(root,'index.html')).href);
    await page.waitForFunction(()=>window.mono&&document.querySelector('canvas').width>0);
    await page.waitForTimeout(700);
    const original=await page.evaluate(()=>mono.getProject());
    check('Abre offline com a casa moderna em 3D',original.pieces.length>60&&original.kind==='modern');
    await page.screenshot({path:path.join(out,'01-apresentacao.png'),fullPage:true});
    await page.locator('#play').click();await page.waitForTimeout(750);
    check('Animação avança',await page.evaluate(()=>mono.getStatus().playing&&mono.getStatus().time>0));
    await page.locator('#play').click();const paused=await page.evaluate(()=>mono.getStatus().time);await page.waitForTimeout(150);
    check('Pausa mantém tempo',await page.evaluate(t=>mono.getStatus().time===t,paused));
    await page.locator('#steps [data-step="3"]').click();
    check('Navegação por etapa',await page.evaluate(()=>mono.getStatus().time>8&&mono.getStatus().time<9));
    await page.locator('#explode').click();check('Vista explodida',await page.evaluate(()=>mono.getStatus().exploded));
    await page.screenshot({path:path.join(out,'02-vista-explodida.png'),fullPage:true});
    await page.locator('#openManual').click();check('Manual abre',await page.locator('#manualDialog').isVisible());
    await page.waitForFunction(()=>!document.getElementById('exportManual').disabled);
    await page.locator('#manualGrid button').first().click();check('Manual seleciona etapa',await page.evaluate(()=>mono.getStatus().time<3));
    check('Logo MONO no cabeçalho',await page.locator('.brand-logo').evaluate(img=>img.complete&&img.naturalWidth>100));
    await page.waitForFunction(()=>[...document.querySelectorAll('[data-model] img')].every(img=>img.src.startsWith('data:image/png')));
    check('Seletor com 8 maquetes ilustradas',await page.locator('[data-model]').count()===8);
    await page.locator('#nightToggle').click();check('Modo noite',await page.evaluate(()=>mono.getStatus().night));
    await page.waitForTimeout(300);await page.screenshot({path:path.join(out,'11-modo-noite.png'),fullPage:true});await page.locator('#nightToggle').click();
    await page.locator('#cutLevel').evaluate(el=>{el.value='3';el.dispatchEvent(new Event('input',{bubbles:true}));});
    check('Corte por andar oculta os andares de cima',await page.evaluate(()=>mono.getStatus().hiddenByCut>10));
    await page.locator('[data-view="back"]').click();await page.waitForTimeout(900);await page.screenshot({path:path.join(out,'12-corte-vista-fundos.png'),fullPage:true});
    await page.locator('#cutLevel').evaluate(el=>{el.value=el.max;el.dispatchEvent(new Event('input',{bubbles:true}));});
    check('Corte volta a mostrar tudo',await page.evaluate(()=>mono.getStatus().hiddenByCut===0));
    await page.locator('#spinToggle').click();check('Giro 360°',await page.evaluate(()=>mono.getStatus().spin));await page.locator('[data-view="front"]').click();
    check('Vista interrompe o giro',await page.evaluate(()=>!mono.getStatus().spin));
    await page.locator('#waveAll').click();check('Todos os personagens acenam',await page.evaluate(()=>mono.getStatus().actingCount===mono.getStatus().figureCount&&mono.getStatus().figureCount>0));
    await page.locator('[data-model="townhouse"]').click();check('Troca para o sobrado urbano',await page.evaluate(()=>mono.getStatus().model==='townhouse'&&mono.getProject().title==='Sobrado urbano'));
    await page.waitForTimeout(400);await page.screenshot({path:path.join(out,'13-sobrado-urbano.png'),fullPage:true});
    await page.locator('[data-model="modern"]').click();check('Volta para a casa moderna',await page.evaluate(()=>mono.getStatus().model==='modern'));
    await page.locator('#editMode').click();check('38 tipos de peças: 12 formas, 12 estilo LEGO e 14 de casa',await page.locator('[data-part]').count()===38&&await page.locator('#legoLibrary [data-part]').count()===12&&await page.locator('#homeLibrary [data-part]').count()===14);
    check('10 personagens prontos e sorteio',await page.locator('#figureLibrary [data-figure]').count()===10&&await page.locator('#randomFigure').count()===1);
    await page.locator('#emptyPreset').click();await page.locator('#confirmAction').click();check('Bancada vazia',await page.evaluate(()=>mono.getProject().pieces.length===0));
    await page.locator('#undo').click();check('Desfazer restaura a casa e o nome',await page.evaluate(()=>mono.getProject().pieces.length>60&&mono.getProject().title==='Casa moderna'));
    await page.locator('#redo').click();
    for(const type of ['brick','plate','cube','beam','arch','wedge','cylinder','sphere','cone','wheel','panel','eye'])await page.locator(`[data-part="${type}"]`).click();
    check('Todas as formas podem ser adicionadas',await page.evaluate(()=>mono.getProject().pieces.length===12));
    await page.locator('[data-library="legoLibrary"]').click();
    check('Miniaturas 3D das peças LEGO',await page.locator('#legoLibrary img').evaluateAll(images=>images.every(img=>img.src.startsWith('data:image/png'))));
    for(const type of ['tile','round','technic','stairs','window','door','fence','gear','ring','plant','tree','lamp'])await page.locator(`#legoLibrary [data-part="${type}"]`).click();
    check('Todas as peças estilo LEGO podem ser adicionadas',await page.evaluate(()=>mono.getProject().pieces.filter(p=>['tile','round','technic','stairs','window','door','fence','gear','ring','plant','tree','lamp'].includes(p.type)).length===12));
    await page.locator('[data-library="homeLibrary"]').click();
    const homeTypes=['palm','glasspanel','railing','slats','water','lounger','sofa','bed','table','chair','shelf','kitchen','pendant','campfire'];
    for(const type of homeTypes)await page.locator(`#homeLibrary [data-part="${type}"]`).click();
    check('Todas as peças de casa e jardim podem ser adicionadas',await page.evaluate(types=>mono.getProject().pieces.filter(p=>types.includes(p.type)).length===14,homeTypes));
    check('Miniaturas 3D das peças de casa',await page.locator('#homeLibrary img').evaluateAll(images=>images.every(img=>img.src.startsWith('data:image/png'))));
    await page.locator('[data-library="figureLibrary"]').click();
    await page.locator('#figureLibrary [data-figure="0"]').click();await page.locator('#randomFigure').click();
    check('Personagens pronto e sorteado',await page.evaluate(()=>{const figures=mono.getProject().pieces.filter(p=>p.type==='figure');return figures.length===2&&figures[0].name==='Exploradora'&&figures[0].fig.accessory==='backpack';}));
    check('Editor de personagem aparece',await page.locator('#figureEditor').isVisible());
    await page.locator('#figHair').selectOption('crown');await page.locator('#figFace').selectOption('wink');await page.locator('#figPrint').selectOption('tie');await page.locator('#figAccessory').selectOption('cape');
    await page.locator('#figSkin').evaluate(el=>{el.value='#8d5524';el.dispatchEvent(new Event('change',{bubbles:true}));});
    check('Personagem customizável: cabelo, rosto, estampa, acessório e pele',await page.evaluate(()=>{const f=mono.getProject().pieces.at(-1).fig;return f.hair==='crown'&&f.face==='wink'&&f.print==='tie'&&f.accessory==='cape'&&f.skin==='#8d5524';}));
    await page.locator('#undo').click();check('Desfazer customização',await page.evaluate(()=>mono.getProject().pieces.at(-1).fig.skin!=='#8d5524'));await page.locator('#redo').click();
    await page.locator('[data-action="dance"]').click();check('Personagem dança',await page.evaluate(()=>mono.getStatus().action==='dance'));
    await page.locator('#liveToggle').click();check('Cena viva desliga',await page.evaluate(()=>!mono.getStatus().liveScene));await page.locator('#liveToggle').click();
    check('Cena viva liga e anima peças',await page.evaluate(()=>mono.getStatus().liveScene&&mono.getStatus().animatedCount>=5));
    await page.screenshot({path:path.join(out,'10-pecas-lego-personagens.png'),fullPage:true});
    await page.locator('[data-library="partsLibrary"]').click();
    await page.locator('#projectTitle').fill('Minha criação livre');await page.locator('#projectTitle').press('Tab');
    await page.locator('#posX').fill('2.25');await page.locator('#posX').press('Tab');
    await page.locator('#posY').fill('2');await page.locator('#posY').press('Tab');
    await page.locator('#sizeX').fill('2.5');await page.locator('#sizeX').press('Tab');
    await page.locator('#rotZ').fill('35');await page.locator('#rotZ').press('Tab');
    await page.locator('#pieceColors [data-color="#3f7d5a"]').click();
    check('Posição, dimensão, rotação e cor editáveis',await page.evaluate(()=>{const p=mono.getProject().pieces.at(-1);return p.pos[0]===2.25&&p.pos[1]===2&&p.size[0]===2.5&&p.rot[2]===35&&p.color==='#3f7d5a';}));
    await page.locator('#duplicate').click();check('Duplicação',await page.evaluate(()=>mono.getProject().pieces.length===41));
    await page.locator('#deletePiece').click();check('Exclusão',await page.evaluate(()=>mono.getProject().pieces.length===40));
    await page.locator('#undo').click();check('Desfazer exclusão',await page.evaluate(()=>mono.getProject().pieces.length===41));
    const built=await page.evaluate(()=>mono.getProject());
    const downloadPromise=page.waitForEvent('download');await page.locator('#saveProject').click();const download=await downloadPromise;
    const saved=path.join(out,'projeto-teste.json');await download.saveAs(saved);
    assert.deepEqual(JSON.parse(fs.readFileSync(saved,'utf8')),built);results.push('Exporta JSON sem perda');
    await page.reload();await page.waitForFunction(()=>window.mono);assert.deepEqual(await page.evaluate(()=>mono.getProject()),built);results.push('Restaura automaticamente após recarregar');
    await page.locator('#editMode').click();await page.locator('#housePreset').click();await page.locator('#confirmAction').click();
    check('Exemplo casa',await page.evaluate(()=>mono.getProject().title==='Minha casa'));
    await page.screenshot({path:path.join(out,'03-casa-editor.png'),fullPage:true});
    await page.locator('#carPreset').click();await page.locator('#confirmAction').click();check('Exemplo veículo',await page.evaluate(()=>mono.getProject().pieces.some(p=>p.type==='wheel')));
    await page.screenshot({path:path.join(out,'04-veiculo-editor.png'),fullPage:true});
    await page.locator('#rocketPreset').click();await page.locator('#confirmAction').click();check('Exemplo foguete',await page.evaluate(()=>mono.getProject().title==='Meu foguete'));
    for(const [preset,kind] of [['modernPreset','modern'],['townhousePreset','townhouse']]){await page.locator('#'+preset).click();await page.locator('#confirmAction').click();check('Exemplo '+kind+' no editor',await page.evaluate(k=>mono.getProject().kind===k&&mono.getStatus().figureCount>=2,kind));}
    await page.locator('#cityPreset').click();await page.locator('#confirmAction').click();
    check('Exemplo praça LEGO com personagens',await page.evaluate(()=>mono.getProject().kind==='city'&&mono.getStatus().figureCount===4&&mono.getProject().pieces.some(p=>p.type==='door')));
    for(const preset of ['cityPreset','crewPreset','modernPreset','townhousePreset']){await page.locator('#'+preset).click();await page.locator('#confirmAction').click();await page.reload();await page.waitForFunction(()=>window.mono);check('Exemplo '+preset+' é restaurado após recarregar',await page.evaluate(kind=>mono.getProject().kind===kind,preset.replace('Preset','')));await page.locator('#editMode').click();}
    await page.locator('#cityPreset').click();await page.locator('#confirmAction').click();
    await page.locator('#resetView').click();await page.screenshot({path:path.join(out,'08-praca-lego.png'),fullPage:true});
    await page.locator('#crewPreset').click();await page.locator('#confirmAction').click();
    check('Exemplo turma de personagens',await page.evaluate(()=>mono.getProject().kind==='crew'&&mono.getStatus().figureCount===7));
    await page.locator('#resetView').click();await page.screenshot({path:path.join(out,'09-turma-personagens.png'),fullPage:true});
    await page.locator('#fileInput').setInputFiles(saved);await page.locator('#confirmAction').click();
    assert.deepEqual(await page.evaluate(()=>mono.getProject()),built);results.push('Importa JSON sem perda');
    await page.locator('#fileInput').setInputFiles({name:'invalido.json',mimeType:'application/json',buffer:Buffer.from('{"format":"outro"}')});
    await page.waitForTimeout(200);assert.deepEqual(await page.evaluate(()=>mono.getProject()),built);results.push('Arquivo inválido preserva construção');
    const capturePromise=page.waitForEvent('download');await page.locator('#capture').click();await (await capturePromise).saveAs(path.join(out,'captura-exportada.png'));results.push('Exporta imagem PNG');
    await page.locator('#previewBuild').click();check('Criação livre também anima',await page.evaluate(()=>mono.getStatus().playing&&mono.getStatus().mode==='present'));
    await page.locator('#play').click();
    const mobileContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await mobileContext.setOffline(true);
    const mobile=await mobileContext.newPage();await mobile.goto(pathToFileURL(path.join(root,'index.html')).href);await mobile.waitForFunction(()=>window.mono);
    check('Layout móvel sem rolagem horizontal',await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
    await mobile.screenshot({path:path.join(out,'05-mobile.png'),fullPage:true});
    await mobile.locator('#editMode').click();await mobile.locator('[data-part="sphere"]').click();
    check('Editor funciona em tela pequena',await mobile.locator('#inspector').isVisible());
    await page.locator('#editMode').click();await page.locator('#emptyPreset').click();await page.locator('#confirmAction').click();
    await page.locator('[data-part="sphere"]').click();await page.locator('#resetView').click();
    const canvas=await page.locator('canvas').boundingBox();const cx=canvas.x+canvas.width/2,cy=canvas.y+canvas.height/2-15;
    await page.mouse.click(cx,cy);check('Seleciona peça pela cena 3D',await page.evaluate(()=>mono.getStatus().selected!==null));
    const beforeDrag=await page.evaluate(()=>mono.getProject().pieces[0].pos);
    await page.mouse.move(cx,cy);await page.mouse.down();await page.mouse.move(cx+65,cy,{steps:8});await page.mouse.up();
    const afterDrag=await page.evaluate(()=>mono.getProject().pieces[0].pos);
    check('Arrastar move a peça com encaixe na grade',afterDrag[0]!==beforeDrag[0]&&Number.isInteger(afterDrag[0]*4));
    await page.locator('#undo').click();assert.deepEqual(await page.evaluate(()=>mono.getProject().pieces[0].pos),beforeDrag);results.push('Desfaz movimento por arraste');
    await page.keyboard.press('ArrowRight');check('Atalho de teclado move peça',await page.evaluate(x=>mono.getProject().pieces[0].pos[0]===x+.25,beforeDrag[0]));
    const beforePan=await page.evaluate(()=>mono.getProject());await page.keyboard.down('Shift');await page.mouse.move(cx-150,cy-110);await page.mouse.down();await page.mouse.move(cx-100,cy-70,{steps:5});await page.mouse.up();await page.keyboard.up('Shift');
    assert.deepEqual(await page.evaluate(()=>mono.getProject()),beforePan);results.push('Mover câmera preserva construção');
    await page.locator('#emptyPreset').click();await page.locator('#confirmAction').click();
    await page.locator('[data-part="plate"]').click();await page.locator('#deselect').click();await page.locator('[data-part="brick"]').click();
    check('Empilhamento automático pousa a peça sobre a placa',await page.evaluate(()=>{const [plate,brick]=mono.getProject().pieces;return plate.pos[1]===.1&&brick.pos[1]===.45;}));
    await page.keyboard.press('r');check('Tecla R gira 90°',await page.evaluate(()=>mono.getProject().pieces[1].rot[1]===90));
    await page.keyboard.press('Control+c');await page.keyboard.press('Control+v');check('Copiar e colar',await page.evaluate(()=>mono.getProject().pieces.length===3));
    await page.locator('#emptyPreset').click();await page.locator('#confirmAction').click();await page.locator('#housePreset').click();await page.locator('#confirmAction').click();
    await page.locator('#editorPanel').evaluate(el=>{el.scrollTop=0;});await page.screenshot({path:path.join(out,'06-construcao-livre.png'),fullPage:true});
    check('Nenhum erro JavaScript',errors.length===0);
    const report={passed:results.length,checks:results,errors,originalPieces:original.pieces.length,offline:true};
    fs.writeFileSync(path.join(out,'resultado.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
