const {chromium}=require('./test-tools/node_modules/playwright');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..');
const out=path.join(root,'verificacao');fs.mkdirSync(out,{recursive:true});
const results=[];
const check=(name,fn)=>{assert.ok(fn,name);results.push(name);};
(async()=>{
  const browser=await chromium.launch({executablePath:'C:/Users/agilb/AppData/Local/ms-playwright/chromium-1187/chrome-win/chrome.exe',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  try{
    const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
    await context.setOffline(true);
    const page=await context.newPage(),errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    await page.goto(pathToFileURL(path.join(root,'index.html')).href);
    await page.waitForFunction(()=>window.mono&&document.querySelector('canvas').width>0);
    await page.waitForTimeout(700);
    const original=await page.evaluate(()=>mono.getProject());
    check('Abre offline com modelo 3D',original.pieces.length>100);
    await page.screenshot({path:path.join(out,'01-apresentacao.png'),fullPage:true});
    await page.locator('#play').click();await page.waitForTimeout(750);
    check('Animação avança',await page.evaluate(()=>mono.getStatus().playing&&mono.getStatus().time>0));
    await page.locator('#play').click();const paused=await page.evaluate(()=>mono.getStatus().time);await page.waitForTimeout(150);
    check('Pausa mantém tempo',await page.evaluate(t=>mono.getStatus().time===t,paused));
    await page.locator('#steps [data-step="3"]').click();
    check('Navegação por etapa',await page.evaluate(()=>mono.getStatus().time>8&&mono.getStatus().time<9));
    await page.locator('#explode').click();check('Vista explodida',await page.evaluate(()=>mono.getStatus().exploded));
    await page.screenshot({path:path.join(out,'02-vista-explodida.png'),fullPage:true});
    await page.locator('#openManual').click();check('Manual abre',await page.locator('#manualDialog').isVisible());
    await page.waitForFunction(()=>!document.getElementById('exportManual').disabled);
    await page.locator('#manualGrid button').first().click();check('Manual seleciona etapa',await page.evaluate(()=>mono.getStatus().time<3));
    await page.locator('#editMode').click();check('12 tipos de peças',await page.locator('[data-part]').count()===12);
    await page.locator('#emptyPreset').click();await page.locator('#confirmAction').click();check('Bancada vazia',await page.evaluate(()=>mono.getProject().pieces.length===0));
    await page.locator('#undo').click();check('Desfazer restaura robô e nome',await page.evaluate(()=>mono.getProject().pieces.length>100&&mono.getProject().title==='Robô explorador'));
    await page.locator('#redo').click();
    for(const type of ['brick','plate','cube','beam','arch','wedge','cylinder','sphere','cone','wheel','panel','eye'])await page.locator(`[data-part="${type}"]`).click();
    check('Todas as formas podem ser adicionadas',await page.evaluate(()=>mono.getProject().pieces.length===12));
    await page.locator('#projectTitle').fill('Minha criação livre');await page.locator('#projectTitle').press('Tab');
    await page.locator('#posX').fill('2.25');await page.locator('#posX').press('Tab');
    await page.locator('#posY').fill('2');await page.locator('#posY').press('Tab');
    await page.locator('#sizeX').fill('2.5');await page.locator('#sizeX').press('Tab');
    await page.locator('#rotZ').fill('35');await page.locator('#rotZ').press('Tab');
    await page.locator('#pieceColors [data-color="#294c45"]').click();
    check('Posição, dimensão, rotação e cor editáveis',await page.evaluate(()=>{const p=mono.getProject().pieces.at(-1);return p.pos[0]===2.25&&p.pos[1]===2&&p.size[0]===2.5&&p.rot[2]===35&&p.color==='#294c45';}));
    await page.locator('#duplicate').click();check('Duplicação',await page.evaluate(()=>mono.getProject().pieces.length===13));
    await page.locator('#deletePiece').click();check('Exclusão',await page.evaluate(()=>mono.getProject().pieces.length===12));
    await page.locator('#undo').click();check('Desfazer exclusão',await page.evaluate(()=>mono.getProject().pieces.length===13));
    const built=await page.evaluate(()=>mono.getProject());
    const downloadPromise=page.waitForEvent('download');await page.locator('#saveProject').click();const download=await downloadPromise;
    const saved=path.join(out,'projeto-teste.json');await download.saveAs(saved);
    assert.deepEqual(JSON.parse(fs.readFileSync(saved,'utf8')),built);results.push('Exporta JSON sem perda');
    await page.reload();await page.waitForFunction(()=>window.mono);assert.deepEqual(await page.evaluate(()=>mono.getProject()),built);results.push('Restaura automaticamente após recarregar');
    await page.locator('#editMode').click();await page.locator('#housePreset').click();await page.locator('#confirmAction').click();
    check('Exemplo casa',await page.evaluate(()=>mono.getProject().title==='Minha casa'));
    await page.screenshot({path:path.join(out,'03-casa-editor.png'),fullPage:true});
    await page.locator('#carPreset').click();await page.locator('#confirmAction').click();check('Exemplo veículo',await page.evaluate(()=>mono.getProject().pieces.some(p=>p.type==='wheel')));
    await page.screenshot({path:path.join(out,'04-veiculo-editor.png'),fullPage:true});
    await page.locator('#rocketPreset').click();await page.locator('#confirmAction').click();check('Exemplo foguete',await page.evaluate(()=>mono.getProject().title==='Meu foguete'));
    await page.locator('#fileInput').setInputFiles(saved);await page.locator('#confirmAction').click();
    assert.deepEqual(await page.evaluate(()=>mono.getProject()),built);results.push('Importa JSON sem perda');
    await page.locator('#fileInput').setInputFiles({name:'invalido.json',mimeType:'application/json',buffer:Buffer.from('{"format":"outro"}')});
    await page.waitForTimeout(200);assert.deepEqual(await page.evaluate(()=>mono.getProject()),built);results.push('Arquivo inválido preserva construção');
    const capturePromise=page.waitForEvent('download');await page.locator('#capture').click();await (await capturePromise).saveAs(path.join(out,'captura-exportada.png'));results.push('Exporta imagem PNG');
    await page.locator('#previewBuild').click();check('Criação livre também anima',await page.evaluate(()=>mono.getStatus().playing&&mono.getStatus().mode==='present'));
    await page.locator('#play').click();
    const mobileContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await mobileContext.setOffline(true);
    const mobile=await mobileContext.newPage();await mobile.goto(pathToFileURL(path.join(root,'index.html')).href);await mobile.waitForFunction(()=>window.mono);
    check('Layout móvel sem rolagem horizontal',await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
    await mobile.screenshot({path:path.join(out,'05-mobile.png'),fullPage:true});
    await mobile.locator('#editMode').click();await mobile.locator('[data-part="sphere"]').click();
    check('Editor funciona em tela pequena',await mobile.locator('#inspector').isVisible());
    await page.locator('#editMode').click();await page.locator('#emptyPreset').click();await page.locator('#confirmAction').click();
    await page.locator('[data-part="sphere"]').click();await page.locator('#resetView').click();
    const canvas=await page.locator('canvas').boundingBox();const cx=canvas.x+canvas.width/2,cy=canvas.y+canvas.height/2-15;
    await page.mouse.click(cx,cy);check('Seleciona peça pela cena 3D',await page.evaluate(()=>mono.getStatus().selected!==null));
    const beforeDrag=await page.evaluate(()=>mono.getProject().pieces[0].pos);
    await page.mouse.move(cx,cy);await page.mouse.down();await page.mouse.move(cx+65,cy,{steps:8});await page.mouse.up();
    const afterDrag=await page.evaluate(()=>mono.getProject().pieces[0].pos);
    check('Arrastar move a peça com encaixe na grade',afterDrag[0]!==beforeDrag[0]&&Number.isInteger(afterDrag[0]*4));
    await page.locator('#undo').click();assert.deepEqual(await page.evaluate(()=>mono.getProject().pieces[0].pos),beforeDrag);results.push('Desfaz movimento por arraste');
    await page.keyboard.press('ArrowRight');check('Atalho de teclado move peça',await page.evaluate(x=>mono.getProject().pieces[0].pos[0]===x+.25,beforeDrag[0]));
    const beforePan=await page.evaluate(()=>mono.getProject());await page.keyboard.down('Shift');await page.mouse.move(cx-150,cy-110);await page.mouse.down();await page.mouse.move(cx-100,cy-70,{steps:5});await page.mouse.up();await page.keyboard.up('Shift');
    assert.deepEqual(await page.evaluate(()=>mono.getProject()),beforePan);results.push('Mover câmera preserva construção');
    await page.locator('#emptyPreset').click();await page.locator('#confirmAction').click();await page.locator('#housePreset').click();await page.locator('#confirmAction').click();
    await page.locator('#editorPanel').evaluate(el=>{el.scrollTop=0;});await page.screenshot({path:path.join(out,'06-construcao-livre.png'),fullPage:true});
    check('Nenhum erro JavaScript',errors.length===0);
    const report={passed:results.length,checks:results,errors,originalPieces:original.pieces.length,offline:true};
    fs.writeFileSync(path.join(out,'resultado.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
